CREATE TABLE click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id BIGINT NOT NULL REFERENCES links (id),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer VARCHAR(2048)
);

CREATE INDEX idx_click_events_link_id ON click_events (link_id);
